### ISSUE TITLE
What's the roadmap?

### ISSUE THREAD

**Issue by sjkv** [biocore-ntnu/pyranges#1]
First of all, thanks so much for all the work you already put into this. I have been tentatively working with your package and think this is very promising. I am sure many people would be very happy to have a Ranges package of this quality in their python toolbox. I have two questions:

1. Is there any roadmap? Can you give any estimate when you'll get to work on this package again and if and when you would recommend starting to use this package? Btw, I am already (test-)using the package with some success.
2. Would you be interested in some pull requests, or do you still want to experiment with the package design and it's too early for outside contributions?

Thanks!

**Comment by endrebak** [comment]
Thanks for trying my package. What you see is a first draft. It is already as fast and memory-efficient as R GRanges, which is promising. 

1) I just finished SICER2, which is the first paper I hope to publish, so I'll start on pyranges again soon. Like within two weeks. PyRanges is the project of mine I like the most and my top priority and I hope to publish a paper on PyRanges within six months.

2) Ideas and discussion here in the issues would be more interesting. Did you have any particular ideas in mind? 
I'm restarting work on PyRanges by rewriting and merging the underlying libraries (NCLS, sorted_nearest, and potentially PyRles) in C++/Cython. This means there is a good risk that PRs will be scrapped due to huge rewrites.
For pull requests I would be more interested in stuff I have been unable to achieve. The number one thing I would like to do is parallelize many of the underlying algorithms. I have been able to do this in Python, but it is very inefficient: the speedup is not very high. I will be able to achieve good parallelization in C++ though.

**Comment by sjkv** [comment]
Very good news, I am happy to hear it! I also read your note on biostars, and already expected that you wouldn't benefit too much from 'python-level' contributions at the moment. I'll gather notes if I miss some functionality while I use pyranges and get back to you if I think I have some use cases that may also be interesting for others!

**Comment by endrebak** [comment]
I am also working on a GenomicFeatures-library alongside. 

One problem with pure-Python contributions is that the code can be very slow for large datasets.

**Comment by endrebak** [comment]
One thing I have been wondering about is what to do in case the range is too wide to display properly. I guess truncating the columns `Chromosome Strand Start End` to `Position` in the display and only have one column in the displayed output like

```
Position
chr1:100-200:+
```

without changing the underlying data would be an improvement.

But this is something that should be able to change in the settings.

In case it is still too wide, I guess I will have to remove a few columns and just display `...` instead.

**Comment by endrebak** [comment]
Since the future release of Pandas2 based on PyArrow will make it necessary to update PyRanges I have decided to not do any change to the underlying library now.  

I would appreciate suggestions for a roadmap.

* faster bam reading
* implement k-next (like bedtools k-closest)
* lots of small stuff to fix, I am sure. What they are, I have no idea.
