### ISSUE TITLE
serialization for multiprocessing

### ISSUE THREAD

**Issue by stephenkraemer** [biocore-ntnu/pyranges#12]
Hi again,
as usual I am super-thrilled at how this is coming along.

I found that I often want to pass a PyRanges instance to a function which I want to use in parallel (using multiprocessing). I can of course pass the underlying dataframe, and then reconstruct the PyRanges within the child processes. However, i) PyRanges construction for large sets of regions takes some time ii) if i use the same function outside of the context of multiprocessing, I do want to pass a PyRanges instance directly. So it would be just a little bit more convenient if the PyRanges class would be serializable. 

Do you have any plans / thoughts on that? In the simplest case, __setstate__ and __getstate__ could automate the 'serialize the underlying DF, then reconstruct the PyRanges' part. I am not Cython-savy enough to know whether there is a more performant alternative...

Thanks!

**Comment by endrebak** [comment]
PyRanges is already multitCPU with ray. Have you seen https://biocore-ntnu.github.io/pyranges/using-multiple-cores.html ?

No need to do anything yourself

**Comment by endrebak** [comment]
I also have a method `apply_chunks` for multi-cpu methods which are row-based.

**Comment by endrebak** [comment]
Also, you can create a PyRanges from a dict of dfs, which is trivial to serialize.

```
import pyranges as pr
cpg = pr.data.cpg()
print(cpg.dfs)
cpg2 = pr.PyRanges(cpg.dfs)
`
``

**Comment by endrebak** [comment]
Your question has made me realize that I should write a page about the pyranges internals in the docs. It’s simple really; it is just a dict of dfs. Since splitting the data on chromosomes/strands to perform chromosome/strandwise operations and then merging them into one data frame afterwards is silly expensive, pyranges objects contain a dict of dfs. The .df property of pyranges fools you into thinking it is represented in one 2D table, but this is not so :)

So constructing a pyranges from one df might take some time since it splits the data, but if you give a dict of dfs per chromosome (and/or strand it takes no time at all to create a pyranges object.

Anyways, closing this soon if you have no follow-up questions or comments.

**Comment by endrebak** [comment]
See #40 also :)
