### ISSUE TITLE
How to create/add multiple metadata columns?

### ISSUE THREAD

**Issue by jnasser3** [biocore-ntnu/pyranges#27]
What is the best way to add multiple metadata columns to a PyRanges object simultaneously (or to create a PyRanges object from a dataframe that has many metadata columns)? 

The documentation describes adding one metadata column at a time, but it doesn't provide the syntax for multiple columns.

**Comment by endrebak** [comment]
The current way would perhaps be to add them to the dataframe that you create a PyRanges from.

This is actually a problem I should think more about. One Pythonic way would be 

```
for col in "col1 col2 col3".split():
    gr[col] = col
``` 

but this does not work since `[]` is for coordinate-based lookups.

You can use 

```
import pyranges as pr
gr = pr.data.f1()
for col in "col1 col2 col3".split():
    setattr(gr, col, col)
# +--------------+-----------+-----------+------------+-----------+--------------+------------+------------+------------+
# | Chromosome   |     Start |       End | Name       |     Score | Strand       | col1       | col2       | col3       |
# | (category)   |   (int32) |   (int32) | (object)   |   (int64) | (category)   | (object)   | (object)   | (object)   |
# |--------------+-----------+-----------+------------+-----------+--------------+------------+------------+------------|
# | chr1         |         3 |         6 | interval1  |         0 | +            | col1       | col2       | col3       |
# | chr1         |         8 |         9 | interval3  |         0 | +            | col1       | col2       | col3       |
# | chr1         |         5 |         7 | interval2  |         0 | -            | col1       | col2       | col3       |
# +--------------+-----------+-----------+------------+-----------+--------------+------------+------------+------------+
# Stranded PyRanges object has 3 rows and 9 columns from 1 chromosomes.
```

But I consider this unidiomatic. I should create an insert-method for single columns like `gr.insert(<position>, <colname>, <value>)`, like pandas has.

**Comment by jnasser3** [comment]
The use case I had in mind was actually to make a PyRanges object from a dataframe with the metadata columns, but it wasn't clear to me what the right syntax would be. 

Since Chromosome, Start, End were required, I was hoping for a syntax such as

`pr.PyRanges(chromosomes=df.chr, starts=df.start, ends=df.end, metadata=df)` or something like that. 

It seems that `pr.PyRanges(df)` is suitable as long as there are columns named 'Chromosome', 'Start' and 'End'. The files I work with typically use 'chr','start','end' - it is a bit cumbersome to have to rename these columns every time. Is there a way to load all the metadata columns without renaming the columns in the dataframe? If not it's okay.

**Comment by stephenkraemer** [comment]
The naming convention is an admittedly very minor, but frequent
usability issue that I also encounter often. I can control the column names
in my own data, but most external data don't use the 'Chromosome', 'Start',
'End' convention. (Mostly 'chr'/'chrom', 'start', 'end') So I need to
rename the columns when I initialize the pyranges object, and change the
names back to the original when I pass the dataframe on to other functions
which expect the original naming convention. But this is really a minor
issue, just to give another user experience.

Am Mi., 18. Sept. 2019 um 17:57 Uhr schrieb jnasser3 <
notifications@github.com>:

**Comment by endrebak** [comment]
@jnasser3 That is a good point. I am going to have to think hard before adding more arguments to the constructor, but I really want to make it easier to create PyRanges without having to rename columns.

@stephenkraemer  

Thanks! I have considered the problem, and I appreciate the feedback.

I would appreciate suggestions for how to fix it, but I think most solutions would add too much complexity. 

The best solution for now is likely to make functions for reading and writing PyRanges that do this column conversion for you.

Renaming columns in pandas is as easy as `df.rename(columns={"chr": "Cromosome", "start": "Start", ...})`

**Comment by endrebak** [comment]
One solution: when creating PyRanges from a df, if not all required names are there, try a conversion

```
df.rename(columns={"chr": "Cromosome", "start": "Start", "end": "End", "stop": "End", "strand": "Strand", "seqnames": "Chromosome"})
```

Big downside: implicit conversions happening without the users knowledge. If the user wants an unstranded df and therefore sets the name to `strand`, the above method would create a Stranded df. 

Might be better with a utility-function in pyranges called `pr.rename_df()`.

**Comment by stephenkraemer** [comment]
thanks for the quick reply! Yes, renaming is trivial, I didn't mean to imply that pyranges should take care of renaming, I like its no-nonsense API. My observation is: in several of our projects, there is a hard convention that the GRanges columns are called 'chr'/'chrom', 'start', 'end'. Many functions and packages used in these projects expect this. It's not a big issue to rename the columns at the beginning and end of each interaction with pyranges, for sure. But thats potentially a lot of renaming calls for me, and it would just be even more convenient if pyranges could accept the 'chr', 'start', 'end' names directly, ie. without renaming the columns. Thus, I could at any point access gr.df and pass it to a function without an additional renaming step, because the df column names would have remained 'chr', 'start', 'end'. 

But yes, right now I can do 

``` python
gr = pr.PyRanges(rename_to_pr(df)) 
```

and then later 
```
foo(rename_pr(gr.df))
```

And that's completely fine. It would just be even nicer, if renaming would not be necessary at all because PyRanges would accept 'chr', 'start' and 'end' directly. But I am aware there are many more important features to add before you ever come to that :)

**Comment by endrebak** [comment]
I do not think this is possible. You often interact with the pure dataframes (using apply and friends). 

```python
gr.apply(lambda df: df.assign({"Chromosome": "chr" + df.Chromosome.astype(str)}) 
```

Then you need one and only one name, since dataframes cannot have multiple names for the same column. If you allow both chr and Chromosome then libraries using PyRanges, but operating on the dataframes themselves, would fail when accessing the Chromosome (or one of the other required columns) if they do not use the same naming convention.

I should really write something about my design choices (alternatives I considered, why something is/is not possible etc).

**Comment by endrebak** [comment]
I think I have an idea for how to add slack to overlap-operations: 

```
1. before doing the operations, duplicate the Start and End columns,
   but rename to <UUID + Start>, <UUID + End>
2. call slack on the gr
3. do operation as usual
4. after the operation is done, replace Start and End 
with <UUID+Start> and <UUID+End> and drop the latter
```

Two more thIngs I need to think about:

1) in some situations you probably only want to add 5' slack or 3' slack. (This is not applicable to the merge/cluster operations, since these are on the same pyranges and hence do not matter `I1+5'slack == i2 + 3'slack` if I1 and I2 are two consecutive intervals.) 

2) in other cases you might want to add a different slack to the two, like 1Kbp to 5' and 500bp to 3'.

Should the slack-argument take a dict of `{"3": 1000, "5": 500}` or just `{"3": 1000}` if no 5' extension is desired and just an int if the two cases are equal? Will need to think about this.


If I still think this is a good idea after the weekend I will implement it :)

**Comment by stephenkraemer** [comment]
> If you allow both chr and Chromosome then libraries using PyRanges, but operating on the dataframes themselves, would fail when accessing the Chromosome (or one of the other required columns) if they do not use the same naming convention
Yes, that's exactly what I was experiencing - my libraries use another naming convention for historical reasons, so they fail when accessing gr.df. But I wasn't thinking about the bigger picture - in all likelihood there will be many libraries interacting with pyranges and it makes sense that there should be one obvious nomenclature everyone can rely on. Thanks for your time!!

**Comment by endrebak** [comment]
One of the main goals of PyRanges was to make it as straightforward as possible to work with pandas 🐼 ❤️ dataframes in genomics, so for the reason above allowing different naming schemes is out. But I appreciate you letting me know about pain points.
