### ISSUE TITLE
Use of git tags for releases

### ISSUE THREAD

**Issue by cfriedline** [biocore-ntnu/pyranges#29]
Hi - thanks for the great work and continuing to enhance this package. We're getting great use out of it. Would it be possible to incorporate git tagging/releases to match with what's in pypi? That would make tracking changes, especially breaking ones, much more straightforward since the tag would capture the whole repo, not just individual commit messages.

**Comment by endrebak** [comment]
Thanks for the request. I am eager to make this package and repo more useful. 

1) Can you describe your use-case?

2) Do you use git directly to download pyranges? I thought people would use pypi, the master is actually the develop branch since I am the only developer.
 
3) Do you have an online guide to describe more or less what you want? Is it that for each pypi release, you want to know the exact git tag? 

Sorry for being obtuse.

**Comment by cfriedline** [comment]
@endrebak No problem - I did not think you were being obtuse. Yes, I do build packages from repos often, and it's very convenient to be able to checkout a tag and install. Perhaps more usefully, when a new build is posted to pypi, it is extremely helpful to go back to the repo and be able to get the code exactly as it was when the deployment to pypi was done, assuming the process of deployment is tied to the git repo. This model is followed by many promient python projects, especially those which build wheels. A good example might be: https://github.com/ipython/ipython/releases. Anyway, I hope that helps.

**Comment by endrebak** [comment]
That is a use-case I never considered. Thanks! I still call pyranges beta
because of my relative immaturity with packaging, versioning and
distributing etc., the beta is really not about the software itself.

I will use git tags and a development branch from now on. I guess I should
implement a pipeline to do commiting and pushing to pypi all in one. I see
here that releases can be created programatically:
https://developer.github.com/v3/repos/releases/#create-a-release

Endre

**Comment by endrebak** [comment]
I just uploaded another version to github, will try to make a tag for it when uploading to PyPI.

May I ask why you use github instead of pypi?

**Comment by endrebak** [comment]
I have started creating git releases. I will also create feature branches to avoid breaking master, but master might not always be equal to a PYPI-release. Closing this, but feel free to re-open or create new issues :)

**Comment by endrebak** [comment]
Now I have protected the master branch so that all tests need to pass and any code has to be reviewed before the master is updated. If you want to be a reviewer just ping me.

**Comment by cfriedline** [comment]
Is this no longer happening?

**Comment by endrebak** [comment]
Is the master failing? :)

**Comment by endrebak** [comment]
Oh, sorry. No, I have not been tagging the releases. The command line tools for it felt kinda wonky, I do have a changelog though. Also, there is little automation in it, I have to remember to do it each time :/

**Comment by endrebak** [comment]
I would appreciate PRs for scripts/workflows for creating and tagging releases, I am swamped with my PhD work right now :)
