### ISSUE TITLE
Bioconda package?

### ISSUE THREAD

**Issue by bnelsj** [biocore-ntnu/pyranges#7]
Hi, this looks like a promising library that could replace pybedtools in my workflow. Are there any plans to add it as a package in the bioconda channel?

**Comment by endrebak** [comment]
Yes, eventually, but I update the package [so often](https://github.com/biocore-ntnu/pyranges/blob/master/CHANGELOG), that I do not want to add it to conda yet. Updating a package on conda is slightly time-consuming and I would rather use my time developing the library.

All the dependencies need to be in conda too, which they currently are not.

I'm leaving this open as I am sure it is a question that will pop up often. And if others want to add pyranges to bioconda, feel free :) (Please do it all in one file then, so that I can update directly on the github webpage.)

**Comment by endrebak** [comment]
Is there any reason why you cannot do `pip install pyranges` btw? Just wondering :)

**Comment by fgypas** [comment]
+1 for conda package as you can include it easier as a dependency in workflows (e.g. snakekame https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management)

**Comment by bnelsj** [comment]
Thanks for the response. I'm also interested in using it as a workflow dependency. Pip installation works fine for now though.

**Comment by endrebak** [comment]
Okay, I will get started. I have some free time now anyways :) Dunno how long it will take :)

**Comment by endrebak** [comment]
It is not in yet, but here is the PR:

https://github.com/bioconda/bioconda-recipes/pull/15206

If the build fails, I should be able to fix it by the weekend, I hope.

**Comment by endrebak** [comment]
Huzzah, it is done. Feel free to re-open or create a new issue if something does not work as expected :)
